site_name: Cloney Documentation
site_description: Documentation for Cloney, the dynamic template generator for Git repositories.
repo_name: ArthurSudbrackIbarra/cloney
repo_url: https://github.com/ArthurSudbrackIbarra/cloney
copyright: Copyright &copy; 2023 Arthur Sudbrack Ibarra

theme:
  name: material
  palette:
    # Palette toggle for light mode.
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode.
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/cloney-logo-no-text.png
  favicon: images/cloney-logo-no-text.png
  language: en
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.sections

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Cloney Template Repositories: cloney-template-repositories.md
  - User's Path:
      - users/index.md
      - Providing Custom Variables: users/providing-custom-variables.md
  - Creator's Path:
      - creators/index.md
      - The .cloney.yaml Metadata File: creators/cloney-metadata-file.md
      - Acessing Variables: creators/accessing-template-variables.md
      - Dynamic File Generation: creators/dynamic-file-generation.md
      - Cloney Template Functions:
          - creators/functions/index.md
          - os: creators/functions/os.md
          - arch: creators/functions/arch.md
      - Go Template Tutorials: creators/go-template-tutorials.md
  - Cloney Command-Line Interface (CLI): cloney-cli.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ./docs
      check_paths: false
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/ua-parser-js/src/ua-parser.min.js
  - scripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArthurSudbrackIbarra
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arthur-sudbrack-ibarra-88399423a/
