on:
  # Trigger when a PR is created against the main branch.
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  # Trigger when a commit is pushed to the main branch.
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Test Docker
        run: docker run --rm hello-world
